# Get all posts
GET http://localhost:3001/api/posts HTTP/1.1

###

# Get all posts order by comments count
GET http://localhost:3001/api/posts?sortOption=discussed HTTP/1.1

###

# Get all posts order by likes
GET http://localhost:3001/api/posts?sortOption=likes HTTP/1.1

###

# Get all users drafts
GET http://localhost:3001/api/posts/drafts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFlYjI3NWI0YjAxMTI2MmRmYTZjYTkiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTcwNjA5ODU0NCwiZXhwIjoxNzA2NTMwNTQ0fQ.Np48aDQey3fkMpiVbDnTZIkdSaE9ZeSP3pkDOAUZUzY

###

# Get posts with type
GET http://localhost:3001/api/posts?type=Видео HTTP/1.1

###

# Get posts by page
GET http://localhost:3001/api/posts?page=1 HTTP/1.1

###

# Get posts by tag
GET http://localhost:3001/api/posts?tag=тег_1 HTTP/1.1

###

# Search posts by words in title
POST http://localhost:3001/api/posts/search?title=text video HTTP/1.1

###

# Get posts with filter by user
GET http://localhost:3001/api/posts?userId=65aeb270b4b011262dfa6ca5 HTTP/1.1

###

# Get post by id
GET http://localhost:3001/api/posts/166fd1b8-6348-42c3-88bd-a3ac5ca6b6bd HTTP/1.1

###

# Create a new post of "Видео" type
POST http://localhost:3001/api/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWIxMWQ4Mzg4NjNiZDFmMjE4NTFmOGQiLCJlbWFpbCI6InVzZXIyM0Bub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwibmFtZSI6Iktla3MiLCJpYXQiOjE3MDYxMDYyNDgsImV4cCI6MTcwNjUzODI0OH0.NErcb6KgSiUutiuBdBMN2H2E3Pry0iYd_IPBG6VEenk

{
  "type": "Видео",
  "videoTitle": "aaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  "videoUrl": "https://www.youtube.com/watch?v=cwyTleTL06Y",
  "tags": ["tag_1", "DAFUQ"]
}

###

# Create a new post of "Текст" type
POST http://localhost:3001/api/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFlYjI3NWI0YjAxMTI2MmRmYTZjYTkiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTcwNjA5ODU0NCwiZXhwIjoxNzA2NTMwNTQ0fQ.Np48aDQey3fkMpiVbDnTZIkdSaE9ZeSP3pkDOAUZUzY

{
  "type": "Текст",
  "textTitle": "pmdfniofgijbiojfn;ls,dv;jdfijb",
  "textAnons": "text anons text anons text anons text anons",
  "text": "Расширенный текст публикации",
  "tags": ["tag_1", "DAFUQ"]
}

###

# Create a new post of "Цитата" type
POST http://localhost:3001/api/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFlYjI3NWI0YjAxMTI2MmRmYTZjYTkiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTcwNjA5ODU0NCwiZXhwIjoxNzA2NTMwNTQ0fQ.Np48aDQey3fkMpiVbDnTZIkdSaE9ZeSP3pkDOAUZUzY

{
  "type": "Цитата",
  "cite": "Я запрещаю вам срать",
  "citeAuthor": "Стэтхем",
  "tags": ["Стетхэм", "Пацан", "тЕГ_1"]
}

###

# Create a new post of "Фото" type
POST http://localhost:3001/api/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFlYjI3NWI0YjAxMTI2MmRmYTZjYTkiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTcwNjA5ODU0NCwiZXhwIjoxNzA2NTMwNTQ0fQ.Np48aDQey3fkMpiVbDnTZIkdSaE9ZeSP3pkDOAUZUzY

{
  "type": "Фото",
  "photo": "photo_file_path",
  "tags": ["тег_1", "тег_1", "ТЕГ_1", "даa", "tag_5", "tag_6", "tag_7", "tag_8", "tag_10"]
}

###

# Create a new post of "Ссылка" type
POST http://localhost:3001/api/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFlYjI3NWI0YjAxMTI2MmRmYTZjYTkiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTcwNjA5ODU0NCwiZXhwIjoxNzA2NTMwNTQ0fQ.Np48aDQey3fkMpiVbDnTZIkdSaE9ZeSP3pkDOAUZUzY

{
  "type": "Ссылка",
  "url": "https://www.youtube.com/watch?v=cwyTleTL06Y",
  "urlDescription": "Description"
}

###

# Delete the post by id
DELETE http://localhost:3001/api/posts/5562f2a9-dd9c-4601-b10f-9a09c6a1b497 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFlYjI3NWI0YjAxMTI2MmRmYTZjYTkiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTcwNjA5ODU0NCwiZXhwIjoxNzA2NTMwNTQ0fQ.Np48aDQey3fkMpiVbDnTZIkdSaE9ZeSP3pkDOAUZUzY

###

# Update post by id
PATCH http://localhost:3001/api/posts/965838a2-91ef-4e00-b99f-f3c5334f9e29 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFlYjI3NWI0YjAxMTI2MmRmYTZjYTkiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTcwNjA5ODU0NCwiZXhwIjoxNzA2NTMwNTQ0fQ.Np48aDQey3fkMpiVbDnTZIkdSaE9ZeSP3pkDOAUZUzY
Content-Type: application/json

{
  "cite": "Я не не запрещаю вам срать",
  "citeAuthor": "Стетхем",
  "publishDate": "2024-01-01T00:00:11.000Z"
}

###

# Repost
POST http://localhost:3001/api/posts/f4111e59-774e-4dde-80ff-321e4480ec9d/repost HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFlYjI3NWI0YjAxMTI2MmRmYTZjYTkiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTcwNjA5ODU0NCwiZXhwIjoxNzA2NTMwNTQ0fQ.Np48aDQey3fkMpiVbDnTZIkdSaE9ZeSP3pkDOAUZUzY

###

# Toggle like on post
POST http://localhost:3001/api/posts/166fd1b8-6348-42c3-88bd-a3ac5ca6b6bd/likes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFlYjI3NWI0YjAxMTI2MmRmYTZjYTkiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTcwNjA5ODU0NCwiZXhwIjoxNzA2NTMwNTQ0fQ.Np48aDQey3fkMpiVbDnTZIkdSaE9ZeSP3pkDOAUZUzY

###
