-- AlterTable
ALTER TABLE "posts" ALTER COLUMN "video_title" DROP NOT NULL,
ALTER COLUMN "video_url" DROP NOT NULL,
ALTER COLUMN "text_title" DROP NOT NULL,
ALTER COLUMN "text_anons" DROP NOT NULL,
ALTER COLUMN "text" DROP NOT NULL,
ALTER COLUMN "cite" DROP NOT NULL,
ALTER COLUMN "cite_author" DROP NOT NULL,
ALTER COLUMN "photo" DROP NOT NULL,
ALTER COLUMN "url" DROP NOT NULL,
ALTER COLUMN "url_description" DROP NOT NULL;
