# Create a new user
POST http://localhost:3004/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "name": "Keks",
  "password": "123456"
}

###

# Login user by email and password
POST http://localhost:3004/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3004/api/auth/65ad0523608aa38470cde18c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFlNzUxYzBjMzA4MWUxOTNjMDI5Y2YiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNzA1OTMzOTIwLCJleHAiOjE3MDU5MzM5ODB9.X-LDnDXymc2nooUAyNkfOIT7r1xdfmbvbkhGVAqTJaw

###

# Get new JWT pair
POST http://localhost:3004/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFlNzUxYzBjMzA4MWUxOTNjMDI5Y2YiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNzA1OTMzOTIwLCJleHAiOjE3MDU5MzM5ODB9.X-LDnDXymc2nooUAyNkfOIT7r1xdfmbvbkhGVAqTJaw

###

# Check user token
POST http://localhost:3004/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFlNzUxYzBjMzA4MWUxOTNjMDI5Y2YiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNzA1OTMzOTIwLCJleHAiOjE3MDU5MzM5ODB9.X-LDnDXymc2nooUAyNkfOIT7r1xdfmbvbkhGVAqTJaw
