# Get all comments for post
GET http://localhost:3001/api/posts/5562f2a9-dd9c-4601-b10f-9a09c6a1b497/comments HTTP/1.1

###

# Get all comments for post with page
GET http://localhost:3001/api/posts/5562f2a9-dd9c-4601-b10f-9a09c6a1b497/comments?page=2 HTTP/1.1

###


# Create a new comment for post
POST http://localhost:3001/api/posts/5562f2a9-dd9c-4601-b10f-9a09c6a1b497/comments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFlYjI3NWI0YjAxMTI2MmRmYTZjYTkiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTcwNjA5ODU0NCwiZXhwIjoxNzA2NTMwNTQ0fQ.Np48aDQey3fkMpiVbDnTZIkdSaE9ZeSP3pkDOAUZUzY
Content-Type: application/json

{
  "message": "This is text"
}

###

# Delete comment by id
DELETE http://localhost:3001/api/posts/7ccf69b6-1ed3-4c0d-b39a-fcbf12bdfe88/comments/123378dd-124b-4d35-9972-8b9d7ddb1658 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFlYjI3NWI0YjAxMTI2MmRmYTZjYTkiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTcwNjA5ODU0NCwiZXhwIjoxNzA2NTMwNTQ0fQ.Np48aDQey3fkMpiVbDnTZIkdSaE9ZeSP3pkDOAUZUzY

###
