# Create a new user
POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "username": "keks",
  "name": "Keks",
  "birthDate": "2012-02-22",
  "password": "123456"
}

###

# Login user by email and password
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###

# Get new JWT pair
POST http://localhost:3000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsInVzZXJuYW1lIjoia2VrcyIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNzA1ODQyMjU1LCJleHAiOjE3MDU4NDIzMTV9.htZ_Gr_lGeFkPZfGL2pjxLJ_KDX0nZPq3BtzaxAesVc

###

# Create a new post
POST http://localhost:3000/api/blog HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsInVzZXJuYW1lIjoia2VrcyIsIm5hbWUiOiJLZWtzIiwiaWF0IjoxNzA1ODQyMjU1LCJleHAiOjE3MDU4NDIzMTV9.htZ_Gr_lGeFkPZfGL2pjxLJ_KDX0nZPq3BtzaxAesVc
Content-Type: application/json

{
  "title": "Check",
  "descriptio": "Description_check",
  "content": "Content_check",
  "tags": ["tag_1", "tag_2"]
}

###
